name: Post Merge

on:
  push:
    branches:
      - master

jobs:
  build-quality:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: type check
        run: npm run type-check

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
