name: Pull Request

on: 
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]   # adjust as needed
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint:silent

      - name: type check
        run: npm run type-check

      - name: Test
        run: npm test

      - name: Coverage
        run: npm run test:coverage

      - name: Compare coverage
        run: npm run coverage:report > coverage-report.txt

      - name: Comment coverage
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('coverage-report.txt', 'utf8');
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });

      - name: Build
        run: npm run build
     
